// Knockout JavaScript library v1.3.0ctp
// (c) Steven Sanderson - http://knockoutjs.com/
// License: MIT (http://www.opensource.org/licenses/mit-license.php)

(function(window,undefined){ 
function b(d){throw d;}var n=void 0,o=null,p=window.ko={};p.b=function(d,e){for(var c=d.split("."),a=window,f=0;f<c.length-1;f++)a=a[c[f]];a[c[c.length-1]]=e};p.h=function(d,e,c){d[e]=c};
p.a=new function(){function d(a,f){if(a.tagName!="INPUT"||!a.type)return!1;if(f.toLowerCase()!="click")return!1;var g=a.type.toLowerCase();return g=="checkbox"||g=="radio"}var e=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,c={click:1,dblclick:1,mousedown:1,mouseup:1,mousemove:1,mouseover:1,mouseout:1,mouseenter:1,mouseleave:1};return{ga:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],j:function(a,f){for(var g=0,c=a.length;g<c;g++)f(a[g])},g:function(a,f){if(typeof a.indexOf=="function")return a.indexOf(f);
for(var g=0,c=a.length;g<c;g++)if(a[g]===f)return g;return-1},Aa:function(a,f,c){for(var d=0,e=a.length;d<e;d++)if(f.call(c,a[d]))return a[d];return o},M:function(a,f){var c=p.a.g(a,f);c>=0&&a.splice(c,1)},L:function(a,f){for(var a=a||[],c=[],d=0,e=a.length;d<e;d++)c.push(f(a[d]));return c},z:function(a,f){for(var a=a||[],c=[],d=0,e=a.length;d<e;d++)f(a[d])&&c.push(a[d]);return c},A:function(a,f){for(var c=0,d=f.length;c<d;c++)a.push(f[c]);return a},q:function(a){for(;a.firstChild;)p.removeNode(a.firstChild)},
Za:function(a,f){p.a.q(a);f&&p.a.j(f,function(f){a.appendChild(f)})},oa:function(a,f){var c=a.nodeType?[a]:a;if(c.length>0){for(var d=c[0],e=d.parentNode,i=0,k=f.length;i<k;i++)e.insertBefore(f[i],d);i=0;for(k=c.length;i<k;i++)p.removeNode(c[i])}},qa:function(a,f){navigator.userAgent.indexOf("MSIE 6")>=0?a.setAttribute("selected",f):a.selected=f},m:function(a){return(a||"").replace(e,"")},fb:function(a,f){for(var c=[],d=(a||"").split(f),e=0,i=d.length;e<i;e++){var k=p.a.m(d[e]);k!==""&&c.push(k)}return c},
ab:function(a,f){a=a||"";if(f.length>a.length)return!1;return a.substring(0,f.length)===f},Ja:function(a){for(var f=Array.prototype.slice.call(arguments,1),c="return ("+a+")",d=0;d<f.length;d++)f[d]&&typeof f[d]=="object"&&(c="with(sc["+d+"]) { "+c+" } ");return(new Function("sc",c)).call(f[0]||window,f)},Ha:function(a,f){if(f.compareDocumentPosition)return(f.compareDocumentPosition(a)&16)==16;for(;a!=o;){if(a==f)return!0;a=a.parentNode}return!1},P:function(a){return p.a.Ha(a,document)},t:function(a,
f,c){if(typeof jQuery!="undefined"){if(d(a,f))var e=c,c=function(a,f){var c=this.checked;if(f)this.checked=f.Ca!==!0;e.call(this,a);this.checked=c};jQuery(a).bind(f,c)}else typeof a.addEventListener=="function"?a.addEventListener(f,c,!1):typeof a.attachEvent!="undefined"?a.attachEvent("on"+f,function(f){c.call(a,f)}):b(Error("Browser doesn't support addEventListener or attachEvent"))},ua:function(a,f){(!a||!a.nodeType)&&b(Error("element must be a DOM node when calling triggerEvent"));if(typeof jQuery!=
"undefined"){var g=[];d(a,f)&&g.push({Ca:a.checked});jQuery(a).trigger(f,g)}else if(typeof document.createEvent=="function")typeof a.dispatchEvent=="function"?(g=document.createEvent(f in c?"MouseEvents":"HTMLEvents"),g.initEvent(f,!0,!0,window,0,0,0,0,0,!1,!1,!1,!1,0,a),a.dispatchEvent(g)):b(Error("The supplied element doesn't support dispatchEvent"));else if(typeof a.fireEvent!="undefined"){if(f=="click"&&a.tagName=="INPUT"&&(a.type.toLowerCase()=="checkbox"||a.type.toLowerCase()=="radio"))a.checked=
a.checked!==!0;a.fireEvent("on"+f)}else b(Error("Browser doesn't support triggering events"))},d:function(a){return p.D(a)?a():a},Ga:function(a,f){return p.a.g((a.className||"").split(/\s+/),f)>=0},ta:function(a,f,c){var d=p.a.Ga(a,f);if(c&&!d)a.className=(a.className||"")+" "+f;else if(d&&!c){for(var c=(a.className||"").split(/\s+/),d="",e=0;e<c.length;e++)c[e]!=f&&(d+=c[e]+" ");a.className=p.a.m(d)}},Wa:function(a,f){for(var a=p.a.d(a),f=p.a.d(f),c=[],d=a;d<=f;d++)c.push(d);return c},T:function(a){for(var c=
[],d=0,e=a.length;d<e;d++)c.push(a[d]);return c},R:/MSIE 6/i.test(navigator.userAgent),Pa:/MSIE 7/i.test(navigator.userAgent),ha:function(a,c){for(var d=p.a.T(a.getElementsByTagName("INPUT")).concat(p.a.T(a.getElementsByTagName("TEXTAREA"))),e=typeof c=="string"?function(a){return a.name===c}:function(a){return c.test(a.name)},j=[],i=d.length-1;i>=0;i--)e(d[i])&&j.push(d[i]);return j},G:function(a){if(typeof a=="string"&&(a=p.a.m(a))){if(window.JSON&&window.JSON.parse)return window.JSON.parse(a);
return(new Function("return "+a))()}return o},Y:function(a){(typeof JSON=="undefined"||typeof JSON.stringify=="undefined")&&b(Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js"));return JSON.stringify(p.a.d(a))},Va:function(a,c,d){var d=d||{},e=d.params||{},j=d.includeFields||this.ga,i=a;if(typeof a=="object"&&a.tagName=="FORM")for(var i=a.action,
k=j.length-1;k>=0;k--)for(var l=p.a.ha(a,j[k]),q=l.length-1;q>=0;q--)e[l[q].name]=l[q].value;var c=p.a.d(c),m=document.createElement("FORM");m.style.display="none";m.action=i;m.method="post";for(var s in c)a=document.createElement("INPUT"),a.name=s,a.value=p.a.Y(p.a.d(c[s])),m.appendChild(a);for(s in e)a=document.createElement("INPUT"),a.name=s,a.value=e[s],m.appendChild(a);document.body.appendChild(m);d.submitter?d.submitter(m):m.submit();setTimeout(function(){m.parentNode.removeChild(m)},0)}}};
p.b("ko.utils",p.a);p.b("ko.utils.arrayForEach",p.a.j);p.b("ko.utils.arrayFirst",p.a.Aa);p.b("ko.utils.arrayFilter",p.a.z);p.b("ko.utils.arrayGetDistinctValues",p.a.eb);p.b("ko.utils.arrayIndexOf",p.a.g);p.b("ko.utils.arrayMap",p.a.L);p.b("ko.utils.arrayPushAll",p.a.A);p.b("ko.utils.arrayRemoveItem",p.a.M);p.b("ko.utils.fieldsIncludedWithJsonPost",p.a.ga);p.b("ko.utils.getFormFields",p.a.ha);p.b("ko.utils.postJson",p.a.Va);p.b("ko.utils.parseJson",p.a.G);p.b("ko.utils.registerEventHandler",p.a.t);
p.b("ko.utils.stringifyJson",p.a.Y);p.b("ko.utils.range",p.a.Wa);p.b("ko.utils.toggleDomNodeCssClass",p.a.ta);p.b("ko.utils.triggerEvent",p.a.ua);p.b("ko.utils.unwrapObservable",p.a.d);Function.prototype.bind||(Function.prototype.bind=function(d){var e=this,c=Array.prototype.slice.call(arguments),d=c.shift();return function(){return e.apply(d,c.concat(Array.prototype.slice.call(arguments)))}});
p.a.e=new function(){var d=0,e="__ko__"+(new Date).getTime(),c={};return{get:function(a,c){var d=p.a.e.getAll(a,!1);return d===n?n:d[c]},set:function(a,c,d){d===n&&p.a.e.getAll(a,!1)===n||(p.a.e.getAll(a,!0)[c]=d)},getAll:function(a,f){var g=a[e];if(!g){if(!f)return;g=a[e]="ko"+d++;c[g]={}}return c[g]},clear:function(a){var f=a[e];f&&(delete c[f],a[e]=o)}}};
p.a.p=new function(){function d(a,f){var d=p.a.e.get(a,c);d===n&&f&&(d=[],p.a.e.set(a,c,d));return d}function e(a){var c=d(a,!1);if(c)for(var c=c.slice(0),e=0;e<c.length;e++)c[e](a);p.a.e.clear(a);typeof jQuery=="function"&&typeof jQuery.cleanData=="function"&&jQuery.cleanData([a])}var c="__ko_domNodeDisposal__"+(new Date).getTime();return{ba:function(a,c){typeof c!="function"&&b(Error("Callback must be a function"));d(a,!0).push(c)},na:function(a,f){var e=d(a,!1);e&&(p.a.M(e,f),e.length==0&&p.a.e.set(a,
c,n))},u:function(a){if(!(a.nodeType!=1&&a.nodeType!=9)){e(a);var c=[];p.a.A(c,a.getElementsByTagName("*"));for(var a=0,d=c.length;a<d;a++)e(c[a])}},removeNode:function(a){p.u(a);a.parentNode&&a.parentNode.removeChild(a)}}};p.u=p.a.p.u;p.removeNode=p.a.p.removeNode;p.b("ko.cleanNode",p.u);p.b("ko.removeNode",p.removeNode);p.b("ko.utils.domNodeDisposal",p.a.p);p.b("ko.utils.domNodeDisposal.addDisposeCallback",p.a.p.ba);p.b("ko.utils.domNodeDisposal.removeDisposeCallback",p.a.p.na);
p.a.ka=function(d){if(typeof jQuery!="undefined")d=jQuery.clean([d]);else{var e=p.a.m(d).toLowerCase(),c=document.createElement("div"),e=e.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!e.indexOf("<tr")&&[2,"<table><tbody>","</tbody></table>"]||(!e.indexOf("<td")||!e.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""];for(c.innerHTML=e[1]+d+e[2];e[0]--;)c=c.lastChild;d=p.a.T(c.childNodes)}return d};
p.a.pa=function(d,e){p.a.q(d);if(e!==o&&e!==n)if(typeof e!="string"&&(e=e.toString()),typeof jQuery!="undefined")jQuery(d).html(e);else for(var c=p.a.ka(e),a=0;a<c.length;a++)d.appendChild(c[a])};
p.k=function(){function d(){return((1+Math.random())*4294967296|0).toString(16).substring(1)}function e(a,c){if(a)if(a.nodeType==8){var d=p.k.la(a.nodeValue);d!=o&&c.push({Fa:a,Sa:d})}else if(a.nodeType==1)for(var d=0,h=a.childNodes,j=h.length;d<j;d++)e(h[d],c)}var c={};return{U:function(a){typeof a!="function"&&b(Error("You can only pass a function to ko.memoization.memoize()"));var f=d()+d();c[f]=a;return"<\!--[ko_memo:"+f+"]--\>"},va:function(a,d){var e=c[a];e===n&&b(Error("Couldn't find any memo with ID "+
a+". Perhaps it's already been unmemoized."));try{return e.apply(o,d||[]),!0}finally{delete c[a]}},wa:function(a,c){var d=[];e(a,d);for(var h=0,j=d.length;h<j;h++){var i=d[h].Fa,k=[i];c&&p.a.A(k,c);p.k.va(d[h].Sa,k);i.nodeValue="";i.parentNode&&i.parentNode.removeChild(i)}},la:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:o}}}();p.b("ko.memoization",p.k);p.b("ko.memoization.memoize",p.k.U);p.b("ko.memoization.unmemoize",p.k.va);p.b("ko.memoization.parseMemoText",p.k.la);
p.b("ko.memoization.unmemoizeDomNodeAndDescendants",p.k.wa);p.fa={};function x(d){var e=this;if(d)for(var c in d){var a=p.fa[c];typeof a=="function"&&(e=a(e,d[c]))}return e}p.b("ko.extenders",p.fa);p.bb=function(d,e){this.N=d;this.n=function(){this.Oa=!0;e()}.bind(this);p.h(this,"dispose",this.n)};
p.Z=function(){var d=[];this.$=function(e,c){var a=c?e.bind(c):e,f=new p.bb(a,function(){p.a.M(d,f)});d.push(f);return f};this.w=function(e){p.a.j(d.slice(0),function(c){c&&c.Oa!==!0&&c.N(e)})};this.Ma=function(){return d.length};this.extend=x;p.h(this,"subscribe",this.$);p.h(this,"extend",this.extend);p.h(this,"notifySubscribers",this.w);p.h(this,"getSubscriptionsCount",this.Ma)};p.ja=function(d){return typeof d.$=="function"&&typeof d.w=="function"};p.b("ko.subscribable",p.Z);
p.b("ko.isSubscribable",p.ja);p.B=function(){var d=[];return{Ba:function(e){d.push({N:e,ea:[]})},end:function(){d.pop()},ma:function(e){p.ja(e)||b("Only subscribable things can act as dependencies");if(d.length>0){var c=d[d.length-1];p.a.g(c.ea,e)>=0||(c.ea.push(e),c.N(e))}}}}();var y={undefined:!0,"boolean":!0,number:!0,string:!0};function z(d,e){return d===o||typeof d in y?d===e:!1}
p.s=function(d){function e(){if(arguments.length>0){if(!e.equalityComparer||!e.equalityComparer(c,arguments[0]))c=arguments[0],e.w(c);return this}else return p.B.ma(e),c}var c=d;e.o=p.s;e.I=function(){e.w(c)};e.equalityComparer=z;p.Z.call(e);p.h(e,"valueHasMutated",e.I);return e};p.D=function(d){if(d===o||d===n||d.o===n)return!1;if(d.o===p.s)return!0;return p.D(d.o)};p.F=function(d){if(typeof d=="function"&&d.o===p.s)return!0;if(typeof d=="function"&&d.o===p.i&&d.Na)return!0;return!1};
p.b("ko.observable",p.s);p.b("ko.isObservable",p.D);p.b("ko.isWriteableObservable",p.F);
p.Ua=function(d){arguments.length==0&&(d=[]);d!==o&&d!==n&&!("length"in d)&&b(Error("The argument passed when initializing an observable array must be an array, or null, or undefined."));var e=new p.s(d);p.a.j(["pop","push","reverse","shift","sort","splice","unshift"],function(c){e[c]=function(){var a=e(),a=a[c].apply(a,arguments);e.I();return a}});p.a.j(["slice"],function(c){e[c]=function(){var a=e();return a[c].apply(a,arguments)}});e.remove=function(c){for(var a=e(),d=[],g=[],h=typeof c=="function"?
c:function(a){return a===c},j=0,i=a.length;j<i;j++){var k=a[j];h(k)?g.push(k):d.push(k)}e(d);return g};e.Xa=function(c){if(c===n){var a=e();e([]);return a}if(!c)return[];return e.remove(function(a){return p.a.g(c,a)>=0})};e.O=function(c){for(var a=e(),d=typeof c=="function"?c:function(a){return a===c},g=a.length-1;g>=0;g--)d(a[g])&&(a[g]._destroy=!0);e.I()};e.Ea=function(c){if(c===n)return e.O(function(){return!0});if(!c)return[];return e.O(function(a){return p.a.g(c,a)>=0})};e.indexOf=function(c){var a=
e();return p.a.g(a,c)};e.replace=function(c,a){var d=e.indexOf(c);d>=0&&(e()[d]=a,e.I())};p.h(e,"remove",e.remove);p.h(e,"removeAll",e.Xa);p.h(e,"destroy",e.O);p.h(e,"destroyAll",e.Ea);p.h(e,"indexOf",e.indexOf);return e};p.b("ko.observableArray",p.Ua);
p.i=function(d,e,c){function a(){p.a.j(q,function(a){a.n()});q=[]}function f(){if(j&&typeof c.disposeWhen=="function"&&c.disposeWhen())g.n();else{try{a(),p.B.Ba(function(a){q.push(a.$(f))}),h=c.owner?c.read.call(c.owner):c.read()}finally{p.B.end()}g.w(h);j=!0}}function g(){if(arguments.length>0)if(typeof c.write==="function"){var a=arguments[0];c.owner?c.write.call(c.owner,a):c.write(a)}else b("Cannot write a value to a dependentObservable unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");
else return j||f(),p.B.ma(g),h}var h,j=!1;d&&typeof d=="object"?c=d:(c=c||{},c.read=d||c.read,c.owner=e||c.owner);typeof c.read!="function"&&b("Pass a function that returns the value of the dependentObservable");var i=typeof c.disposeWhenNodeIsRemoved=="object"?c.disposeWhenNodeIsRemoved:o,k=o;if(i){k=function(){g.n()};p.a.p.ba(i,k);var l=c.disposeWhen;c.disposeWhen=function(){return!p.a.P(i)||typeof l=="function"&&l()}}var q=[];g.o=p.i;g.La=function(){return q.length};g.Na=typeof c.write==="function";
g.n=function(){i&&p.a.p.na(i,k);a()};p.Z.call(g);c.deferEvaluation!==!0&&f();p.h(g,"dispose",g.n);p.h(g,"getDependenciesCount",g.La);return g};p.i.o=p.s;p.b("ko.dependentObservable",p.i);
(function(){function d(a,f,g){g=g||new c;a=f(a);if(!(typeof a=="object"&&a!==o&&a!==n))return a;var h=a instanceof Array?[]:{};g.save(a,h);e(a,function(c){var e=f(a[c]);switch(typeof e){case "boolean":case "number":case "string":case "function":h[c]=e;break;case "object":case "undefined":var k=g.get(e);h[c]=k!==n?k:d(e,f,g)}});return h}function e(a,c){if(a instanceof Array)for(var d=0;d<a.length;d++)c(d);else for(d in a)c(d)}function c(){var a=[],c=[];this.save=function(d,e){var j=p.a.g(a,d);j>=0?
c[j]=e:(a.push(d),c.push(e))};this.get=function(d){d=p.a.g(a,d);return d>=0?c[d]:n}}p.sa=function(a){arguments.length==0&&b(Error("When calling ko.toJS, pass the object you want to convert."));return d(a,function(a){for(var c=0;p.D(a)&&c<10;c++)a=a();return a})};p.toJSON=function(a){a=p.sa(a);return p.a.Y(a)}})();p.b("ko.toJS",p.sa);p.b("ko.toJSON",p.toJSON);
p.f={l:function(d){if(d.tagName=="OPTION"){if(d.__ko__hasDomDataOptionValue__===!0)return p.a.e.get(d,p.c.options.V);return d.getAttribute("value")}else return d.tagName=="SELECT"?d.selectedIndex>=0?p.f.l(d.options[d.selectedIndex]):n:d.value},J:function(d,e){if(d.tagName=="OPTION")switch(typeof e){case "string":case "number":p.a.e.set(d,p.c.options.V,n);"__ko__hasDomDataOptionValue__"in d&&delete d.__ko__hasDomDataOptionValue__;d.value=e;break;default:p.a.e.set(d,p.c.options.V,e),d.__ko__hasDomDataOptionValue__=
!0,d.value=""}else if(d.tagName=="SELECT")for(var c=d.options.length-1;c>=0;c--){if(p.f.l(d.options[c])==e){d.selectedIndex=c;break}}else{if(e===o||e===n)e="";d.value=e}}};p.b("ko.selectExtensions",p.f);p.b("ko.selectExtensions.readValue",p.f.l);p.b("ko.selectExtensions.writeValue",p.f.J);
p.r=function(){function d(a,c){return a.replace(e,function(a,d){return c[d]})}var e=/\[ko_token_(\d+)\]/g,c=/^[\_$a-z][\_$a-z0-9]*(\[.*?\])*(\.[\_$a-z][\_$a-z0-9]*(\[.*?\])*)*$/i,a=["true","false"];return{G:function(a){a=p.a.m(a);if(a.length<3)return{};for(var c=[],e=o,j,i=a.charAt(0)=="{"?1:0;i<a.length;i++){var k=a.charAt(i);if(e===o)switch(k){case '"':case "'":case "/":e=i;j=k;break;case "{":e=i;j="}";break;case "[":e=i,j="]"}else if(k==j){k=a.substring(e,i+1);c.push(k);var l="[ko_token_"+(c.length-
1)+"]",a=a.substring(0,e)+l+a.substring(i+1);i-=k.length-l.length;e=o}}e={};a=a.split(",");j=0;for(i=a.length;j<i;j++){var l=a[j],q=l.indexOf(":");q>0&&q<l.length-1&&(k=p.a.m(l.substring(0,q)),l=p.a.m(l.substring(q+1)),k.charAt(0)=="{"&&(k=k.substring(1)),l.charAt(l.length-1)=="}"&&(l=l.substring(0,l.length-1)),k=p.a.m(d(k,c)),l=p.a.m(d(l,c)),e[k]=l)}return e},Q:function(d){var e=p.r.G(d),h=[],j;for(j in e){var i=e[j],k;k=i;k=p.a.g(a,p.a.m(k).toLowerCase())>=0?!1:k.match(c)!==o;k&&(h.length>0&&h.push(", "),
h.push(j+" : function(__ko_value) { "+i+" = __ko_value; }"))}h.length>0&&(d=d+", '_ko_property_writers' : { "+h.join("")+" } ");return d}}}();p.b("ko.jsonExpressionRewriting",p.r);p.b("ko.jsonExpressionRewriting.parseJson",p.r.G);p.b("ko.jsonExpressionRewriting.insertPropertyAccessorsIntoJson",p.r.Q);
(function(){function d(a,c,d){for(var h,j=0;h=c.childNodes[j];j++)h.nodeType===1&&e(a,h,d)}function e(a,e,g){var h=!0;if(e.getAttribute(c))h=p.K(e,o,a,g).$a;h&&d(a,e,g)}var c="data-bind";p.c={};p.K=function(a,d,e,h){function j(a){return function(){return q[a]}}function i(){return q}var h=h||{},k=!0,l=h.bindingAttributeName||c,q,m={},s;new p.i(function(){var c;if(!(c=typeof d=="function"?d():d)){var t=a.getAttribute(l),w=h.extraScope;try{var v=" { "+p.r.Q(t)+" } ";c=p.a.Ja(v,e===o?window:e,w)}catch(A){b(Error("Unable to parse binding attribute.\nMessage: "+
A+";\nAttribute value: "+t))}}q=c;if(k)for(var r in q)if(m[r]={valueAccessor:j(r),dataStore:{}},p.c[r]&&typeof p.c[r].init=="function"&&(c=(0,p.c[r].init)(a,m[r].valueAccessor,i,e,m[r]))&&c.controlsDescendantBindings)s!==n&&b(Error("Multiple bindings ("+s+" and "+r+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.")),s=r;for(r in q)p.c[r]&&typeof p.c[r].update=="function"&&(0,p.c[r].update)(a,m[r].valueAccessor,i,e,m[r])},
o,{disposeWhenNodeIsRemoved:a});k=!1;return{$a:s===n}};p.da=function(a,c,e){(!c||c.nodeType!==1)&&b(Error("ko.applyBindingsToDescendants: first parameter should be your view model; second parameter should be a DOM node"));d(a,c,e)};p.ca=function(a,c,d){c&&c.nodeType!==1&&b(Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node"));c=c||window.document.body;e(a,c,d)};p.b("ko.bindingHandlers",p.c);p.b("ko.applyBindings",p.ca);p.b("ko.applyBindingsToDescendants",
p.da);p.b("ko.applyBindingsToNode",p.K)})();p.a.j(["click"],function(d){p.c[d]={init:function(e,c,a,f){return p.c.event.init.call(this,e,function(){var a={};a[d]=c();return a},a,f)}}});p.c.event={init:function(d,e,c,a){var f=e()||{},g;for(g in f)(function(){var f=g;typeof f=="string"&&p.a.t(d,f,function(d){var g,k=e()[f],l=c();try{g=k.apply(a,arguments)}finally{if(g!==!0)d.preventDefault?d.preventDefault():d.returnValue=!1}if(l[f+"Bubble"]===!1)d.cancelBubble=!0,d.stopPropagation&&d.stopPropagation()})})()}};
p.c.submit={init:function(d,e,c,a){typeof e()!="function"&&b(Error("The value for a submit binding must be a function to invoke on submit"));p.a.t(d,"submit",function(c){var g,h=e();try{g=h.call(a,d)}finally{if(g!==!0)c.preventDefault?c.preventDefault():c.returnValue=!1}})}};p.c.visible={update:function(d,e){var c=p.a.d(e()),a=d.style.display!="none";if(c&&!a)d.style.display="";else if(!c&&a)d.style.display="none"}};
p.c.enable={update:function(d,e){var c=p.a.d(e());if(c&&d.disabled)d.removeAttribute("disabled");else if(!c&&!d.disabled)d.disabled=!0}};p.c.disable={update:function(d,e){p.c.enable.update(d,function(){return!p.a.d(e())})}};
p.c.value={init:function(d,e,c){var a=c().valueUpdate||"change",f=!1;p.a.ab(a,"after")&&(f=!0,a=a.substring(5));var g=f?function(a){setTimeout(a,0)}:function(a){a()};p.a.t(d,a,function(){g(function(){var a=e(),f=p.f.l(d);p.F(a)?a(f):(a=c(),a._ko_property_writers&&a._ko_property_writers.value&&a._ko_property_writers.value(f))})})},update:function(d,e){var c=p.a.d(e()),a=p.f.l(d),f=c!=a;c===0&&a!==0&&a!=="0"&&(f=!0);f&&(a=function(){p.f.J(d,c)},a(),d.tagName=="SELECT"&&setTimeout(a,0));d.tagName=="SELECT"&&
(a=p.f.l(d),a!==c&&p.a.ua(d,"change"))}};
p.c.options={update:function(d,e,c){d.tagName!="SELECT"&&b(Error("options binding applies only to SELECT elements"));var a=p.a.L(p.a.z(d.childNodes,function(a){return a.tagName&&a.tagName=="OPTION"&&a.selected}),function(a){return p.f.l(a)||a.innerText||a.textContent}),f=d.scrollTop,g=p.a.d(e());p.a.q(d);if(g){var h=c();typeof g.length!="number"&&(g=[g]);if(h.optionsCaption){var j=document.createElement("OPTION");j.innerHTML=h.optionsCaption;p.f.J(j,n);d.appendChild(j)}c=0;for(e=g.length;c<e;c++){var j=
document.createElement("OPTION"),i=typeof h.optionsValue=="string"?g[c][h.optionsValue]:g[c],k=h.optionsText;optionText=typeof k=="function"?k(g[c]):typeof k=="string"?g[c][k]:i;i=p.a.d(i);optionText=p.a.d(optionText);p.f.J(j,i);j.innerHTML=optionText.toString();d.appendChild(j)}g=d.getElementsByTagName("OPTION");c=h=0;for(e=g.length;c<e;c++)p.a.g(a,p.f.l(g[c]))>=0&&(p.a.qa(g[c],!0),h++);if(f)d.scrollTop=f}}};p.c.options.V="__ko.bindingHandlers.options.optionValueDomData__";
p.c.selectedOptions={ia:function(d){for(var e=[],d=d.childNodes,c=0,a=d.length;c<a;c++){var f=d[c];f.tagName=="OPTION"&&f.selected&&e.push(p.f.l(f))}return e},init:function(d,e,c){p.a.t(d,"change",function(){var a=e();p.F(a)?a(p.c.selectedOptions.ia(this)):(a=c(),a._ko_property_writers&&a._ko_property_writers.value&&a._ko_property_writers.value(p.c.selectedOptions.ia(this)))})},update:function(d,e){d.tagName!="SELECT"&&b(Error("values binding applies only to SELECT elements"));var c=p.a.d(e());if(c&&
typeof c.length=="number")for(var a=d.childNodes,f=0,g=a.length;f<g;f++){var h=a[f];h.tagName=="OPTION"&&p.a.qa(h,p.a.g(c,p.f.l(h))>=0)}}};p.c.text={update:function(d,e){var c=p.a.d(e());if(c===o||c===n)c="";typeof d.innerText=="string"?d.innerText=c:d.textContent=c}};p.c.html={update:function(d,e){var c=p.a.d(e());p.a.pa(d,c)}};p.c.css={update:function(d,e){var c=p.a.d(e()||{}),a;for(a in c)if(typeof a=="string"){var f=p.a.d(c[a]);p.a.ta(d,a,f)}}};
p.c.style={update:function(d,e){var c=p.a.d(e()||{}),a;for(a in c)if(typeof a=="string"){var f=p.a.d(c[a]);d.style[a]=f||""}}};p.c.uniqueName={init:function(d,e){if(e())d.name="ko_unique_"+ ++p.c.uniqueName.Da,p.a.R&&d.mergeAttributes(document.createElement("<input name='"+d.name+"'/>"),!1)}};p.c.uniqueName.Da=0;
p.c.checked={init:function(d,e,c){p.a.t(d,"click",function(){var a;if(d.type=="checkbox")a=d.checked;else if(d.type=="radio"&&d.checked)a=d.value;else return;var f=e();d.type=="checkbox"&&p.a.d(f)instanceof Array?(a=p.a.g(p.a.d(f),d.value),d.checked&&a<0?f.push(d.value):!d.checked&&a>=0&&f.splice(a,1)):p.F(f)?f()!==a&&f(a):(f=c(),f._ko_property_writers&&f._ko_property_writers.checked&&f._ko_property_writers.checked(a))});d.type=="radio"&&!d.name&&p.c.uniqueName.init(d,function(){return!0})},update:function(d,
e){var c=p.a.d(e());if(d.type=="checkbox")d.checked=c instanceof Array?p.a.g(c,d.value)>=0:c,c&&p.a.R&&d.mergeAttributes(document.createElement("<input type='checkbox' checked='checked' />"),!1);else if(d.type=="radio")d.checked=d.value==c,d.value==c&&(p.a.R||p.a.Pa)&&d.mergeAttributes(document.createElement("<input type='radio' checked='checked' />"),!1)}};
p.c.attr={update:function(d,e){var c=p.a.d(e())||{},a;for(a in c)if(typeof a=="string"){var f=p.a.d(c[a]);f===!1||f===o||f===n?d.removeAttribute(a):d.setAttribute(a,f.toString())}}};p.c["with"]={init:function(d,e,c,a,f){f.dataStore.cb=d.innerHTML;return{controlsDescendantBindings:!0}},update:function(d,e,c,a,f,g){p.a.q(d);if(e=p.a.d(e()))p.a.pa(d,f.dataStore.cb),p.da(g||e,d)}};p.c["if"]={init:p.c["with"].init,update:function(d,e,c,a,f){p.c["with"].update(d,e,c,a,f,a)}};
p.c.foreach={init:function(d,e,c,a,f){f.dataStore.Ka=d.innerHTML;p.a.q(d);return{controlsDescendantBindings:!0}},update:function(d,e,c,a,f){var e=p.a.d(e()),g;e&&(g=typeof e.length=="number"?e:p.a.d(e.data));g===o||g===n?p.a.q(d):(typeof g.length!="number"&&b(Error("The 'foreach' binding can only be used with array-like values")),g=e.includeDestroyed?g:p.a.z(g,function(a){return!a._destroy}),p.a.X(d,g,function(a){for(var c=p.a.ka(f.dataStore.Ka),d=0,e=c.length;d<e;d++)c[d].nodeType==1&&p.ca(a,c[d],
{extraScope:{$data:a}});return c},{afterAdd:e.afterAdd,beforeRemove:e.beforeRemove}))}};p.aa=function(){this.renderTemplate=function(){b("Override renderTemplate in your ko.templateEngine subclass")};this.isTemplateRewritten=function(){b("Override isTemplateRewritten in your ko.templateEngine subclass")};this.rewriteTemplate=function(){b("Override rewriteTemplate in your ko.templateEngine subclass")};this.createJavaScriptEvaluatorBlock=function(){b("Override createJavaScriptEvaluatorBlock in your ko.templateEngine subclass")}};
p.b("ko.templateEngine",p.aa);
p.H=function(){var d=/(<[a-z]+\d*(\s+(?!data-bind=)[a-z0-9\-]+(=(\"[^\"]*\"|\'[^\']*\'))?)*\s+)data-bind=(["'])([\s\S]*?)\5/gi;return{Ia:function(d,c){c.isTemplateRewritten(d)||c.rewriteTemplate(d,function(a){return p.H.Ta(a,c)})},Ta:function(e,c){return e.replace(d,function(a,d,e,h,j,i,k){a=p.r.Q(k);return c.createJavaScriptEvaluatorBlock("ko.templateRewriting.applyMemoizedBindingsToNextSibling(function() {                     return (function() { return { "+a+" } })()                 })")+d})},
ya:function(d){return p.k.U(function(c,a){c.nextSibling&&p.K(c.nextSibling,d,a)})}}}();p.b("ko.templateRewriting",p.H);p.b("ko.templateRewriting.applyMemoizedBindingsToNextSibling",p.H.ya);
(function(){function d(c,a,d,g,h){var j=p.a.d(g),h=h||{},i=h.templateEngine||e;p.H.Ia(d,i);d=i.renderTemplate(d,j,h);(typeof d.length!="number"||d.length>0&&typeof d[0].nodeType!="number")&&b("Template engine must return an array of DOM nodes");d&&p.a.j(d,function(a){p.k.wa(a,[g])});switch(a){case "replaceChildren":p.a.Za(c,d);break;case "replaceNode":p.a.oa(c,d);break;case "ignoreTargetNode":break;default:b(Error("Unknown renderMode: "+a))}h.afterRender&&h.afterRender(d,g);return d}var e;p.ra=function(c){c!=
n&&!(c instanceof p.aa)&&b("templateEngine must inherit from ko.templateEngine");e=c};p.W=function(c,a,f,g,h){f=f||{};(f.templateEngine||e)==n&&b("Set a template engine before calling renderTemplate");h=h||"replaceChildren";if(g){var j=g.nodeType?g:g.length>0?g[0]:o;return new p.i(function(){var e=typeof c=="function"?c(a):c,e=d(g,h,e,a,f);h=="replaceNode"&&(g=e,j=g.nodeType?g:g.length>0?g[0]:o)},o,{disposeWhen:function(){return!j||!p.a.P(j)},disposeWhenNodeIsRemoved:j&&h=="replaceNode"?j.parentNode:
j})}else return p.k.U(function(d){p.W(c,a,f,d,"replaceNode")})};p.Ya=function(c,a,e,g){return new p.i(function(){var h=p.a.d(a)||[];typeof h.length=="undefined"&&(h=[h]);h=p.a.z(h,function(a){return e.includeDestroyed||!a._destroy});p.a.X(g,h,function(a){var g=typeof c=="function"?c(a):c;return d(o,"ignoreTargetNode",g,a,e)},e)},o,{disposeWhenNodeIsRemoved:g})};p.c.template={update:function(c,a,d,e){a=p.a.d(a());d=typeof a=="string"?a:a.name;if(typeof a.foreach!="undefined")e=p.Ya(d,a.foreach||[],
{templateOptions:a.templateOptions,afterAdd:a.afterAdd,beforeRemove:a.beforeRemove,includeDestroyed:a.includeDestroyed,afterRender:a.afterRender},c);else var h=a.data,e=p.W(d,typeof h=="undefined"?e:h,{templateOptions:a.templateOptions,afterRender:a.afterRender},c);(a=p.a.e.get(c,"__ko__templateSubscriptionDomDataKey__"))&&typeof a.n=="function"&&a.n();p.a.e.set(c,"__ko__templateSubscriptionDomDataKey__",e)}}})();p.b("ko.setTemplateEngine",p.ra);p.b("ko.renderTemplate",p.W);
p.a.v=function(d,e,c){if(c===n)return p.a.v(d,e,1)||p.a.v(d,e,10)||p.a.v(d,e,Number.MAX_VALUE);else{for(var d=d||[],e=e||[],a=d,f=e,g=[],h=0;h<=f.length;h++)g[h]=[];for(var h=0,j=Math.min(a.length,c);h<=j;h++)g[0][h]=h;h=1;for(j=Math.min(f.length,c);h<=j;h++)g[h][0]=h;for(var j=a.length,i,k=f.length,h=1;h<=j;h++){var l=Math.min(k,h+c);for(i=Math.max(1,h-c);i<=l;i++)g[i][h]=a[h-1]===f[i-1]?g[i-1][h-1]:Math.min(g[i-1][h]===n?Number.MAX_VALUE:g[i-1][h]+1,g[i][h-1]===n?Number.MAX_VALUE:g[i][h-1]+1)}c=
d.length;a=e.length;f=[];h=g[a][c];if(h===n)g=o;else{for(;c>0||a>0;){j=g[a][c];i=a>0?g[a-1][c]:h+1;k=c>0?g[a][c-1]:h+1;l=a>0&&c>0?g[a-1][c-1]:h+1;if(i===n||i<j-1)i=h+1;if(k===n||k<j-1)k=h+1;l<j-1&&(l=h+1);i<=k&&i<l?(f.push({status:"added",value:e[a-1]}),a--):(k<i&&k<l?f.push({status:"deleted",value:d[c-1]}):(f.push({status:"retained",value:d[c-1]}),a--),c--)}g=f.reverse()}return g}};p.b("ko.utils.compareArrays",p.a.v);
(function(){function d(d,c,a){var f=[],d=p.i(function(){var d=c(a)||[];f.length>0&&p.a.oa(f,d);f.splice(0,f.length);p.a.A(f,d)},o,{disposeWhenNodeIsRemoved:d,disposeWhen:function(){return f.length==0||!p.a.P(f[0])}});return{Ra:f,i:d}}p.a.X=function(e,c,a,f){for(var c=c||[],f=f||{},g=p.a.e.get(e,"setDomNodeChildrenFromArrayMapping_lastMappingResult")===n,h=p.a.e.get(e,"setDomNodeChildrenFromArrayMapping_lastMappingResult")||[],j=p.a.L(h,function(a){return a.za}),i=p.a.v(j,c),c=[],k=0,l=[],j=[],q=o,
m=0,s=i.length;m<s;m++)switch(i[m].status){case "retained":var u=h[k];c.push(u);u.C.length>0&&(q=u.C[u.C.length-1]);k++;break;case "deleted":h[k].i.n();p.a.j(h[k].C,function(a){l.push({element:a,index:m,value:i[m].value});q=a});k++;break;case "added":var t=d(e,a,i[m].value),u=t.Ra;c.push({za:i[m].value,C:u,i:t.i});for(var t=0,w=u.length;t<w;t++){var v=u[t];j.push({element:v,index:m,value:i[m].value});q==o?e.firstChild?e.insertBefore(v,e.firstChild):e.appendChild(v):q.nextSibling?e.insertBefore(v,
q.nextSibling):e.appendChild(v);q=v}}p.a.j(l,function(a){p.u(a.element)});a=!1;if(!g){if(f.afterAdd)for(m=0;m<j.length;m++)f.afterAdd(j[m].element,j[m].index,j[m].value);if(f.beforeRemove){for(m=0;m<l.length;m++)f.beforeRemove(l[m].element,l[m].index,l[m].value);a=!0}}a||p.a.j(l,function(a){a.element.parentNode&&a.element.parentNode.removeChild(a.element)});p.a.e.set(e,"setDomNodeChildrenFromArrayMapping_lastMappingResult",c)}})();p.b("ko.utils.setDomNodeChildrenFromArrayMapping",p.a.X);
p.S=function(){function d(){var c=e==0?"jquery.tmpl not detected.\nTo use KO's default template engine, reference jQuery and jquery.tmpl. See Knockout installation documentation for more details.":e==1?"Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.":o;c&&b(Error(c))}var e=function(){if(typeof jQuery=="undefined"||!jQuery.tmpl)return 0;try{if(jQuery.tmpl.tag.tmpl.open.toString().indexOf("__")>=0)return 2}catch(c){}return 1}();this.getTemplateNode=function(c){var a=
document.getElementById(c);a||b(Error("Cannot find template with ID="+c));return a};this.renderTemplate=function(c,a,e){e=e||{};d();if(!(c in jQuery.template)){var g=this.getTemplateNode(c).text;jQuery.template(c,g)}a=[a];c=jQuery.tmpl(c,a,e.templateOptions);c.appendTo(document.createElement("div"));jQuery.fragments={};return c};this.isTemplateRewritten=function(c){d.call(this);if(c in jQuery.template)return!0;return this.getTemplateNode(c).Qa===!0};this.rewriteTemplate=function(c,a){var d=this.getTemplateNode(c);
d.text=a(d.text);d.Qa=!0};this.createJavaScriptEvaluatorBlock=function(c){return"{{ko_code ((function() { return "+c+" })()) }}"};this.xa=function(c,a){document.write("<script type='text/html' id='"+c+"'>"+a+"<\/script>")};p.h(this,"addTemplate",this.xa);e>=2&&(jQuery.tmpl.tag.ko_code={open:"__.push($1 || '');"})};p.S.prototype=new p.aa;p.ra(new p.S);p.b("ko.jqueryTmplTemplateEngine",p.S);
})(window);                  
